site_name: CSharp Generator for Queries
nav:
    - Overview: index.md
    - Installation: installation.md
    - Releases: releases.md
    - Issues: issues.md
    - Contribution: contribute.md
    - Examples: examples.md
    - Getting Help: help.md
theme: readthedocs
    